# de um nome para sua pipeline
name: Pipeline Robot Framework RTM

# ação que desencadeia a execução
on: workflow_dispatch
jobs:
  test:
    name: Testes Regressivos
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://https://franciscoleal.github.io/esteira-rtm/report.html

    steps:
      - name: Projeto de Teste
        uses: actions/checkout@v4
      
      - name: Instalando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - uses: actions/checkout@v4
      - name: Instalando o nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalação de Dependencias do projeto
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install -U pip
          pip install robotframework-browser
          rfbrowser init
          pip install robotframework-screencaplibrary
          pip install --upgrade robotframework-seleniumlibrary
          pip install PyYAML
          pip install python-dotenv
          pip install robotframework-jsonlibrary
          pip install robotframework-faker
          

      - name: Execução dos Testes
        run: |
          robot --outputdir results/ tests/pipe/
      
      - name: Salvando resultado dos testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultado-testes
          path: /results
        
      - name: Configurar Site do relatorio
        uses: actions/configure-pages@v5
        if: always()
        
      - name: Upload do relatorio 
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: results/

      - name: Deploy do relatorio no Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: always()

    
